package io.nirahtech.enumerations;

public enum AnimationType {
    IDLE_RIGHT,
    FRONT_WALK_RIGHT,
    FRONT_RUN_RIGHT,
    BACKWARD_WALK_RIGHT,
    IDLE_JUMP_RIGHT,
    WALK_JUMP_RIGHT,
    RUN_JUMP_RIGHT,

    IDLE_LEFT,
    FRONT_WALK_LEFT,
    FRONT_RUN_LEFT,
    BACKWARD_WALK_LEFT,
    IDLE_JUMP_LEFT,
    WALK_JUMP_LEFT,
    RUN_JUMP_LEFT,

    IDLE_TOP,
    FRONT_WALK_TOP,
    FRONT_RUN_TOP,
    BACKWARD_WALK_TOP,
    IDLE_JUMP_TOP,
    WALK_JUMP_TOP,
    RUN_JUMP_TOP,

    IDLE_BOTTOM,
    FRONT_WALK_BOTTOM,
    FRONT_RUN_BOTTOM,
    BACKWARD_WALK_BOTTOM,
    IDLE_JUMP_BOTTOM,
    WALK_JUMP_BOTTOM,
    RUN_JUMP_BOTTOM;

}
