package io.nirahtech.runtime;

public enum BiomeType {
    // https://outforia.com/types-of-biomes/

    DESERTS_AND_XERIC_SHRUBLANDS,
    TROPICAL_AND_SUBTROPICAL_MOIST_BROADLEAF_FORESTS,
    TROPICAL_AND_SUBTROPICAL_DRY_BROADLEAF_FORESTS,
    TROPICAL_AND_SUBTROPICAL_CONIFEROUS_FORESTS,
    TEMPERATE_BROADLEAF_AND_MIXED_FORESTS,
    TEMPERATE_CONIFEROUS_FORESTS,
    BOREAL_FOREST_AND_TAIGA,
    TROPICAL_AND_SUBTROPICAL_GRASSLAND_SAVANNAS_SHRUBLANDS,
    TEMPERATE_GRASSLAND_SAVANNAS_SHRUBLANDS,
    FLOODED_GRASSLAND_AND_SAVANNAS,
    MONTANE_GRASSLAND_AND_SHRUBLANDS,
    TUNDRA,
    MEDITERANEAN_FORESTSAND_WOODLANDSAND_SCRUBS,
    MANGROVES,
    //
    LARGE_RIVERS,
    LARGE_RIVERS_HEADWATERS,
    LARGE_RIVERS_DELTA,
    SMALL_RIVERS,
    LARGE_LAKES,
    SMALL_LAKES_ECOSYSTEMS,
    XERIC_BASINS,
    //
    POLAR,
    TEMPERATE_SHELF_AND_SEAS,
    TEMPERATE_UPWELLINGS,
    TROPICAL_UPWELLINGS,
    TROPICAL_CORAL,

}
